---
- name: Deploy do Laboratório Docker SysAdmin
  hosts: desktop
  become: yes
  tasks:
    - name: Garantir que a pasta do projeto existe no servidor
      file:
        path: /home/janiovr/lab-automation
        state: directory
        mode: '0755'

    - name: Copiar arquivos do Docker Compose para o servidor
      copy:
        src: ../docker-lab/
        dest: /home/janiovr/lab-automation/

    - name: Subir containers com Docker Compose
      community.docker.docker_compose_v2:
        project_src: /home/janiovr/lab-automation/
        state: present
